### ISSUE TITLE
Included as maintainer in conda-forge recipe

### ISSUE THREAD

**Issue by dipterix** [dfsp-spirit/freesurferformats#27]
Dear @dfsp-spirit , I recently submitted conda-forge recipes that make your open-source R package `freesurferformats` and `pkgfilecache` available on the conda-forge channel.

The goal is to let users to be able to run `conda install r-freesurferformats` to install your excellent R packages within the conda environment.

I have listed you as the maintainer of the corresponding recipes so that you will have write-access to modify and upgrade them in the future. 

If you wish to be listed, please reply to the PR at https://github.com/conda-forge/staged-recipes/pull/20776#pullrequestreview-1157039329 with "I wish to be included as the maintainer of r-freesurferformats and r-pkgfilecache" before Friday, Oct 28, 2022. 

If you do not wish to be listed, please let me know, or simply ignore my request. I will remove you from the maintainer list. There will be no consequence and you can always request to be added in the future.

Thanks : )

**Comment by dfsp-spirit** [comment]
Thanks for letting me know, I have commented in the PR.

**Comment by dfsp-spirit** [comment]
Btw, why do people actually use conda for R? Is it about the system dependencies, like not having to compile stuff that requires external C/C++/Fortran libs? This seams to be the main reason for Python. Or the virtual environments? In all my years with R, I never felt I needed them, not even as a package developer. Maybe because in R the policy is to 'always update everything' if you have issues. I use them a lot in Python though.

In my field (neuroscience) it is often hard to explain to people what conda does and why they need it (it does 2 things they do not care about and that do not exist in Matlab: dependency resolution and creating virtual environments). And when people come with issues, it is most often that they are in the wrong virtual environment. ;)

So conda *seems* to just be another obstacle in the way of people trying to use Python (coming from Matlab). It sure is not, it is useful (and I use it). But that is not obvious in the beginning. And the fact that there is also pip makes it even worse. And therefore, if not needed (as with R), I avoid it.

EDIT: I guess it is useful if your system version of R is outdated, and you want another one but do not have root access, maybe?

**Comment by dipterix** [comment]
Correct, conda is useful in administrated systems. Another scenario is when I want to wrap the whole project as a standalone program (for example: fsl ships a whole conda environment in its program). 

I agree that neuroscientists like to use Matlab because this is how they are trained. They can have lots of reasons not to abandon Matlab, but the most important two reasons are either

* Their labs have code libraries written in Matlab that they are satisfied with the situation (they are not your target customers)
* People don't know other choices, and Matlab "seems" to have existing pipelines/code/infrastructures 

For the second type, if you can provide some killing functions that people cannot do in the past, they are willing to learn, provided you have very detailed instructions. This is why I really appreciate that you could make `freesurferformats` available in R

There seems to be a trend that more and more people (especially in iEEG study) are starting to migrate away from Matlab and embrace the open-source world. My personal guess is because studies like iEEG require a lot of resources (money, equipment, subject). The study results can be hardly statistical significant if there is not enough subjects, hence the gov pushes the grant appliers to share their data & code for reproducibility. That's when dependency resolution and isolated virtual environments kick in. People might still have hard time reproduce others' results, but the grant reviewers know Matlab is definitely not the answer. 

As for Python and R, I chose R because it has lots of existing statistical tools. Its graphics system is also much better and easy to use (I use base-R). Packages like `Rcpp`, `shiny`, `htmlwidgets`, `reticulate` really makes it seamless to run C, C++, html, JavaScript, and Python. This is a perfect situation for running interactive applications when users do not have to worry about to code by themselves.
